driver:
  name: docker
driver_config:
  image: ubuntu:18.04
  provision_command: mkdir -p /run/sshd
transport:
  username: kitchen

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 14.7.17

platforms:
  - name: ubuntu-18.04

suites:
  - name: default
    run_list:
      - recipe[couchbase::default]
    attributes:
      couchbase:
        cluster:
          memory_quota_mb: 256
          index_quota_mb: 256
          password: 'secret'
        server:
          version: '5.1.1'
          edition: 'community'
  - name: install_only
    run_list:
      - recipe[couchbase::install_only]
    attributes:
      couchbase:
        server:
          version: '5.1.1'
          edition: 'community'
