---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  customize:
    memory: 1024

provisioner:
  name: chef_zero

platforms:
- name: debian-7.6
  run_list:
  - recipe[apt]

- name: ubuntu-12.04
  run_list:
  - recipe[apt]

- name: centos-6.5

suites:
- name: server-community
  run_list:
  - recipe[minitest-handler]
  - recipe[couchbase::server]
  - recipe[couchbase::cluster]
  - recipe[couchbase::buckets]
  attributes:
    couchbase:
      cluster:
        name: "dev"
        username: "admin"
        password: "test1234"
        memory_quota_mb: 512
      buckets:
        one:
          cluster: "dev"
          type: "memcached"
          saslpassword: "nevertellanyone"
          memory_quota_mb: 256
          replicas: 0
        two:
          cluster: "dev"
          type: "couchbase"
          saslpassword: "mustbedifferent"
          memory_quota_percent: 0.5
          replicas: 1

- name: server-enterprise
  run_list:
  - recipe[minitest-handler]
  - recipe[couchbase::server]
  - recipe[couchbase::cluster]
  - recipe[couchbase::buckets]
  attributes:
    couchbase:
      server:
        edition: "enterprise"
        version: "2.2.0"
      cluster:
        name: "dev"
        username: "admin"
        password: "test1234"
        memory_quota_mb: 512
      buckets:
        one:
          cluster: "dev"
          type: "memcached"
          saslpassword: "nevertellanyone"
          memory_quota_mb: 256
          replicas: 0
        two:
          cluster: "dev"
          type: "couchbase"
          saslpassword: "mustbedifferent"
          memory_quota_percent: 0.5
          replicas: 1
